name: build
on:
  [pull_request, push]

jobs:
  build:
    name: Test Go
    runs-on: ubuntu-latest
    steps:
      - name: setup env
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash

      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/checkout@v2
      - run: |
          echo $GOPATH
          go test ./... -v
