name: build
on:
  [pull_request, push]

jobs:
  build:
    name: Test Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/checkout@v2
      - run: |
          echo $GOPATH
          go env
#          go test ./... -v
